name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request: 

jobs:
  docker-build-and-run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ["8.3", "8.4", "8.5"]
        redis-image: ["redis:7-alpine", "redis:8-alpine", "valkey/valkey:9-alpine"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and Start Services
        # Pass the matrix value as an environment variable to Docker Compose
        run: PHP_VERSION=${{ matrix.php-version }} REDIS_IMAGE=${{ matrix.redis-image }} docker compose up redis -d --build

      - name: Unit Tests
        run: |
          make run-tests

      - name: Stop Services
        if: always()
        run: PHP_VERSION=${{ matrix.php-version }} REDIS_IMAGE=${{ matrix.redis-image }} docker compose down